# https://travis-ci.org/#!/translate/virtaal
sudo: required
language: python
python:
  - 2.7
install:
  - sudo apt-get install libgnutls-dev
  - sudo apt-get install python-gtk2
  - pip install Sphinx
  - pip install translate-toolkit
  - pip install python-Levenshtein
  - pip install lxml
  - pip install pycurl
script:
  - make docs
  - python setup.py install
notifications:
  email:
    on_failure: change
    on_success: change
